version: '3'
services:
  pg: &base
    # the base postgres container; should be latest LTS.
    image: docker.io/postgres:14-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGUSER=postgres
    ports:
      - 5432:5432
    healthcheck:
      timeout: 10s
      interval: 1s
      test: [CMD, pg_isready, -U, postgres, -h, localhost]
      retries: 10
    volumes:
      - ./:/workspace # should only be used for read-only operations
      - example_tablespace:/data/example_tablespace
      - indices_tablespace:/data/indices_tablespace
volumes:
  example_tablespace:  &local_driver_opts
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: 'size=10m,uid=70' # 70 is the postgres uid
  indices_tablespace: *local_driver_opts
